ministryofjustice/hmpps-approved-premises-e2e

- pages/apply/applyPage.ts
- pages/apply/basePage.ts
- pages/apply/checkYourAnswersPage.ts
- pages/apply/confirmPersonPage.ts
- pages/apply/confirmationPage.ts
- pages/apply/crnPage.ts
- pages/apply/dashboardPage.ts
- pages/apply/index.ts
- pages/apply/listPage.ts
- pages/apply/startPage.ts
- pages/apply/tasklistPage.ts
- tests/apply.spec.ts
This makes the tests a little easier to follow, as well as cleaner. They’re not quite as rigorous as the old Cypress page object (all Apply pages have a single `ApplyPage` class), but this is fine given these are e2e tests.
> Update Apply tests to include page objects

- pages/apply/applyPage.ts
The `role=tab` was removed recently as the automated Accessiblity tests didn’t like it. We can now use a `link` role.
> Update selector for clicking tabs

- playwright.config.ts
Sometimes upstream APIs can be flaky
> Increase timeout to five minutes

- pages/manage/arrivalFormPage.ts
The names of the Key Workers are liable to change so it is more reliable to just grab the first one
> Fix - Mark an arrival

- .github/workflows/ci.yml
- .gitignore
- README.md
- package.json
- pages/apply/crnPage.ts
- pages/assess/listPage.ts
- pages/match/listPage.ts
- pages/workflow/assessmentPage.ts
- pages/workflow/placementRequestPage.ts
- playwright.config.ts
- steps/apply.ts
- steps/assess.ts
- steps/match.ts
- steps/workflow.ts
- test.ts
- testOptions.ts
- tests/apply.spec.ts
- tests/auth.setup.ts
- tests/manage.spec.ts
This adds a new `local` project, which overrides the baseURL of the main config, and also specifies different CRNs, logins, and other assorted variables which differ between the dev and local environments.
We can now run the e2es against local code, which will allow us to debug failures more easily and get ahead of any changes which might break our e2e tests.
> Allow running against local code

- pages/apply/listPage.ts
- pages/apply/placementConfirmPage.ts
- pages/apply/showPage.ts
- pages/assess/listPage.ts
- pages/basePage.ts
- pages/match/listPage.ts
- pages/workflow/listPage.ts
- pages/workflow/placementApplicationPage.ts
- playwright.config.ts
- steps/apply.ts
- steps/assess.ts
- steps/match.ts
- steps/placementApplication.ts
- steps/workflow.ts
- tests/apply.spec.ts
This adds support for us to test the application flow for Placement Applications. Because we're creating more than one application now, we'll need to ensure we're working against the correct application, so we fetch the ID of the created application and use the data IDs to fetch the correct Assessments etc.
Sorry the commit history is not as neat as I'd usually like, but hopefully you can follow.
> Add placement application flow

- pages/workflow/listPage.ts
The ID of the task is now not the Application ID, so we’ve updated the locator in the UI
> Update task selector

- pages/apply/applyPage.ts
- steps/apply.ts
- steps/assess.ts
- tests/apply.spec.ts
Applications are now treated as Emergency if the release date is 28 days or more away, so we need to update the test flow to test for emergency applications. I've also updated the test name and some of the variables.
> Change short notice application to emergency

- steps/apply.ts
The application withdrawl page has changed now so we need to specify a reason instead of just confirming.
> Use withdrawl reason instead of Yes/No

- playwright.config.ts
This will allow us to view videos for failed e2e runs in CI
> Set trace and video to `on`

- pages/manage/arrivalFormPage.ts
- pages/manage/changeDepartureDate.ts
- pages/manage/changePlacementDates.ts
Before, if the tests ran on a day of the month that doesn’t exist in two month’s time, then we end up entering a date that doesn’t exist.
> Input real dates when changing placement dates

- pages/admin/editUser.ts
- pages/apply/applyPage.ts
- pages/basePage.ts
- steps/admin.ts
- steps/placementApplication.ts
- tests/admin.spec.ts
- tests/apply.spec.ts
The E2Es have been failing due to the E2E user not appearing the in the dropdown when assigning an assessment to a user (EG `/tasks/placement-request/{placementRequestId}`). 
For the first Apply test in order to appear in the drop down the user needs to have no 'qualifications' selected from the following list if the Application isn't a special type (Emergency, PIPE, ESAP, LAO) 
But for the second Apply test in order to appear in the drop down the user needs to have the 'emergency' qualification selected from the list
> Assign user roles before performing tests

- pages/manage/markBedOutOfServicePage.ts
Previously we used a date which, at the time, felt like a long time in the future. Now that day has come let's use a date that is always in the future.
> Use dynamic out of service bed date

- steps/apply.ts
This showed up when fixing, but in normal circumstances won’t show up, because the application has no associated bookings or placement requests.
> Remove withdrawlTypePage when withdrawing

- steps/apply.ts
- tests/apply.spec.ts
Before we were blindly clicking on the first withdraw link, which was not always the correct one, so now we filter by the application’s ID first and click on the link in that row to ensure we withdraw the right application.
> Click correct withdraw link

- pages/manage/cancellationPage.ts
- pages/manage/placementPage.ts
- steps/apply.ts
- tests/apply.spec.ts
- tests/manage.spec.ts
We now show an interstitial page regardless of if there are withdrawables present. I’ve also DRYed up some of the withdrawl helpers and made sure we withdraw the correct application by fetching the ID.
> Fix withdrawal tests

- pages/apply/appealApplicationPage.ts
- pages/apply/listPage.ts
- pages/apply/showPage.ts
- pages/assess/confirmationPage.ts
- steps/apply.ts
- steps/assess.ts
- tests/apply.spec.ts
This tests that an appeal can be recorded against a rejected decision if a user has the role 'Appeals manager' - related to [(APS-240) Record appeal decision](https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/1466)
This could likely be extended to include viewing an an appeal once that piece of work is complete.
Have updated `assessApplication`workflow - it now takes a decision argument (e.g. accepted or rejected), and just checks for a success banner, not the exact text of the decision.
> Add test to appeal a decision

- steps/assess.ts
This placement requirement option has been removed since it doesn't map to a question asked during the application
See: https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/1517
> (APS-354) Remove ground floor requirement

- pages/assess/listPage.ts
If there is more than one page of assessments, we need to handle this. We use the same technique we've used for tasks here. It's not the most DRY solution, but I think making is adaptable to different scenarios will be too much of a time sink.
> Handle pagination for assessments

- steps/assess.ts
We have a feature flag that determines whether to show this confirmation screen or not.
It would be good to read the values from the feature flag service but given we will move these tests into the UI repo soon enough it feels like a waste of time at the moment
> Feature flag sufficient information confirmation screen
