ministryofjustice/hmpps-approved-premises-e2e

- tests/apply.spec.ts
This was introduced in https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/718
> Add Additional Circumstances page

- pages/apply/applyPage.ts
- pages/apply/checkYourAnswersPage.ts
- pages/apply/confirmPersonPage.ts
- pages/apply/crnPage.ts
- pages/apply/index.ts
- pages/apply/listPage.ts
- pages/apply/startPage.ts
- pages/assess/assessPage.ts
- pages/assess/confirmationPage.ts
- pages/assess/index.ts
- pages/assess/listPage.ts
- pages/assess/tasklistPage.ts
- pages/basePage.ts
- pages/dashboardPage.ts
- pages/match/confirmPage.ts
- pages/match/confirmationPage.ts
- pages/match/detailsPage.ts
- pages/match/index.ts
- pages/match/listPage.ts
- pages/match/resultsPage.ts
- pages/workflow/assessmentPage.ts
- pages/workflow/index.ts
- pages/workflow/listPage.ts
- pages/workflow/placementRequestPage.ts
- playwright.config.ts
- steps/apply.ts
- steps/assess.ts
- steps/match.ts
- steps/workflow.ts
- tests/apply.spec.ts
This cleans up the Apply tests, and adds a new test for Assess, which runs immediately after the Apply tests have run. In addition to the page objects, I've also added some "step" functions, which add a "cucumber-like" way of defining tests, without the added overhead of adding Cucumber. This will hopefully make the tests a tad more readable an maintainable.
> (1492) Add end to end tests for assess

- package.json
- playwright.config.ts
- steps/assess.ts
The matching information had fallen out of sync with the latest in dev. 
It's hard to find beds that match the correct characteristics in dev so I have opted to have them all as 'not relevant' for now
> Update Matching Information tests

- .eslintrc.json
- package-lock.json
- package.json
- pages/apply/crnPage.ts
- pages/dashboardPage.ts
- pages/manage/arrivalFormPage.ts
- pages/manage/bedPage.ts
- pages/manage/bedsPage.ts
- pages/manage/cancellationPage.ts
- pages/manage/confirmationPage.ts
- pages/manage/createPlacementPage.ts
- pages/manage/extendPlacementFormPage.ts
- pages/manage/markBedOutOfServicePage.ts
- pages/manage/nonarrivalFormPage.ts
- pages/manage/placementConfirmationPage.ts
- pages/manage/placementPage.ts
- pages/manage/premisesListPage.ts
- pages/manage/premisesPage.ts
- steps/manage.ts
- tests/manage.spec.ts
Adds tests for the 'Manage' transaction.
> Add manage tests

- steps/assess.ts
> Change single room matcher

- pages/match/placement-applications/confirmationPage.ts
- pages/match/placement-applications/decisionPage.ts
- pages/match/placement-applications/reviewPage.ts
- steps/placementApplication.ts
Extends existing tests for the above journey.
> Test review placement application journey

- pages/apply/applyPage.ts
- steps/apply.ts
As there are 3 date inputs on this page we can't use the normal method of filling in dates so I have made a custom one
> Add end dates page

- steps/apply.ts
All short notice and emergency plans require this step now
> Add trigger plans page

- tests/apply.spec.ts
We are pausing work on Match in favour of a dahboard for CRU users to manually book, so we'll skip testing the match flow for now.
> Skip match for now

- pages/manage/cancellationPage.ts
- pages/manage/changeDepartureDate.ts
- pages/manage/confirmationPage.ts
- pages/manage/placementPage.ts
- pages/manage/premisesPage.ts
- tests/manage.spec.ts
This adds a test around the functionality for changing the departure date of a booking (FKA extending a booking).
> Add change departure date test

- package-lock.json
- package.json
Now we have updated the Docker image that Playwright runs on (https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/1117) We need to update the version of Playwright here too
> Update playwright to 1.38.0

- package-lock.json
- package.json
- pages/apply/showPage.ts
- steps/assess.ts
The button to create a placement application has moved so we need to update the test
> Update placement application step

- steps/assess.ts
> Update further information tests

- pages/apply/applyPage.ts
- pages/apply/relevantDatesPage.ts
- steps/apply.ts
We have updated this page so the tests need updating. Further I have genericised to helper so we can use it for more than just SEDs. 
I am awaiting this PR: https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/1313 
to be merged so I can correct some typos in *this* PR but just wanted to see if this one would pass in theory
> Update 'end dates' page

- pages/apply/applyPage.ts
Since https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/1332 was merged we need to increase the time for a regular (non-short notice) application to more than 6 months
> Increase time to release date

- pages/apply/listPage.ts
Some of the tests are failing. I don’t know why this has only just started. Could be design system upgrade related.
> Add getByRole to click link

- pages/basePage.ts
- steps/apply.ts
Now https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/1359 is in, we need to update the e2e tests to handle region dropdowns.
> Update Apply tests to handle regions

- steps/assess.ts
- tests/manage.spec.ts
This fixes the still broken booking journey, as well as changing the further information tests to adopt the new flow introduced in https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/1362
> Assorted fixes to tests

- pages/basePage.ts
- pages/manage/premisesListPage.ts
- tests/manage.spec.ts
This will need [this PR](https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/1394) to be merged first
> Update area copy

- steps/assess.ts
This was changed in https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/1427
> Update additional information copy

- steps/apply.ts
This applies some fixes to the tests in the withdrawal journey
> Withdrawal fixes

- pages/apply/showPage.ts
This takes stock of the changes made in https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/1440
> Fix placement application withdrawal journey

- pages/manage/cancellationPage.ts
- steps/apply.ts
- tests/manage.spec.ts
Will fix https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/1451 's breakages
> Update cancellation label and withdrawal reason

- pages/apply/showPage.ts
- pages/dashboardPage.ts
Fix tests failing for content changes for APS-310
> APS-310: Fix tests failing for content changes

- pages/manage/cancellationPage.ts
These have been removed in the UI
> Remove booking cancellation inputs

- steps/assess.ts
- steps/email.ts
- tests/apply/appeal.spec.ts
This validates that an assessor has received an email with the correct body when allocated an assessment.
> Validate allocation emails

- README.md
- package.json
- playwright.config.ts
- steps/assess.ts
- utils/createApplication.spec.ts
Creating applications manually can be a slow and frustrating experience, so this extends the e2e suite to allow us to quickly create applications of different types in the development environment.
> Add a utils suite to quickly create an application

- pages/basePage.ts
- steps/apply.ts
> Fill in phone number

- pages/workflow/listPage.ts
- steps/apply.ts
- steps/assess.ts
- steps/email.ts
- steps/workflow.ts
- test.ts
- testOptions.ts
- tests/apply/appeal.spec.ts
- tests/apply/emergency-application.spec.ts
- tests/apply/short-notice-application.spec.ts
This adds some new test steps to ensure that the emergency / short notice applications are allocated as we expect
> (APS-514) Test emergency and short notice allocations

- steps/apply.ts
- steps/assess.ts
Following https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/1659
> Add contingency plan questions to short notice flow

- steps/apply.ts
I added this for testing locally and I thought it worth including in case we want to use it in tests at a later date.
> Add case manager section to tests

- steps/apply.ts
This no longer exists, since
https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/1670
> Remove RFAP page

- pages/apply/selectIndexOffencePage.ts
- playwright.config.ts
- steps/apply.ts
- test.ts
- testOptions.ts
- tests/apply/appeal.spec.ts
- tests/apply/emergency-application.spec.ts
- tests/apply/no-release-date.spec.ts
- tests/apply/request-further-information.spec.ts
- tests/apply/short-notice-application.spec.ts
- tests/apply/standard-application.spec.ts
- tests/apply/withdraw-application.spec.ts
- tests/withdrawals.spec.ts
- utils/createApplication.spec.ts
This updates the index offence tests, now https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/1728 has been merged and all users have to select an index offence
> Update index offence tests

- pages/manage/createPlacementPage.ts
Now https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/1734 is in we always need to confirm the index offence
> Choose index offence when booking a placement

- pages/assess/tasklistPage.ts
> Update text to “Submit assessment”
